language: c
sudo: false
compiler: gcc
os:
- linux
env:
  matrix:
  - LUA=lua-5.1.5          LUAROCKS=2.2.2
branches:
  only:
  - master
notifications:
  email: false
install:
- ". ./install.sh"
- luarocks install luadoc
script:
- cd docgen
- lua -v build_all.lua
- cd ..
- ". ./deploy.sh"
