name: Build Documentation

# On pull requests, just try and build docs

on:
  pull_request:
      branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0

        # Amend the sf_version file
        - name: Write version
          if: github.event.action == 'closed' && github.event.pull_request.merged == 'true'
            run: |
              git config user.name github
              git config user.email github@github.com
              echo "SF_VERSION = \""$(git rev-parse HEAD)"\"" > "lua/starfall/sfversion.lua"
              git add "lua/starfall/sfversion.lua"
              git commit --amend --no-edit
              git push -f

        # Clone docgen branch, run build_docs.sh in order to build sf_doc.json
        - name: Build Docs
          run: |
            git clone -b docgen --single-branch https://github.com/thegrb93/StarfallEx.git docgen
            chmod -R +xrw .
            cd docgen
            . ./build_docs.sh
